sudo: required

language: python
python:
  - "3.7"
  - "3.9"

services:

before_install:
  
script:
  - ./test_most_active_cookie.py

after_success:
  - cp ./most_active_cookie.py ./most_active_cookie